name: Main Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.3
      - name: Setup Node.js
        uses: re-taro/actions/setup-node@v3.5.4
        with:
          node-version-file: .tool-versions
      - name: Build test
        run: pnpm build
        shell: sh
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.3
      - name: Setup Node.js
        uses: re-taro/actions/setup-node@v3.5.4
        with:
          node-version-file: .tool-versions
      - name: Lint test
        run: pnpm lint
        shell: sh
