name: Main Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0
      - name: Setup Node.js
        uses: re-taro/actions/setup-node@v3.2.1
        with:
          node-version-file: .tool-versions
      - name: Use turborepo cache
        uses: re-taro/actions/turbo-cache@v3.2.1
      - name: Build test
        run: pnpm build
        shell: sh
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0
      - name: Setup Node.js
        uses: re-taro/actions/setup-node@v3.2.1
        with:
          node-version-file: .tool-versions
      - name: Use turborepo cache
        uses: re-taro/actions/turbo-cache@v3.2.1
      - name: Lint test
        run: pnpm lint
        shell: sh
