name: release

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0
      - id: release
        uses: google-github-actions/release-please-action@v3.7.9
        with:
          release-type: node
          include-v-in-tag: false
      - name: Publish to Cloudflare Workers
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm deploy
        shell: sh
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
